# vim:sw=2:et:

language: generic

addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - elixir
      - esl-erlang

before_script:
  # Make sure we use Elixir from Erlang Solutions and not kiex.
  - |
    make --version
    echo YES | kiex implode
    elixir --version
    elixir --version | grep -q 'Elixir 1.6.6'

script: make tests

cache:
  apt: true
