# Generated by Erlang.mk. Edit at your own risk!

src/rabbit_auth_backend_cert_regex.erl:: /root/deps/rabbit_common/include/rabbit.hrl /root/deps/rabbit_common/include/resource.hrl; @touch $@

COMPILE_FIRST +=
