name: CI
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
jobs:
  build-test:
    name: Build and test on Erlang/OTP ${{ matrix.otp-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp-version: [24]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp-version}}
          elixir-version: 1.13.4
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync
      - name: Fetch dependencies
        run: make deps
      - name: Compile
        run: make
      - name: Test
        run: make tests